### ISSUE TITLE
部署成功后的使用问题

### ISSUE THREAD

**Issue by Hison-y** [ixrjog/caesar#4]
大佬你好,我已经把caesar在本地部署跑起来了,发现登录远程服务器不支持密码登录是吧,但是如果用ssh密钥的话会报错com.jcraft.jsch.JSchException: invalid privatekey,网上查了是jcraft版本低导致无法解析那个私钥,有没有什么更好的解决办法呢

**Comment by ixrjog** [comment]
感谢使用！
   caesar不支持密码方式登录（当时觉得安全性差），高版本的openssh生成的密钥对的确无法使用（建议在centos7创建密钥对）
