### ISSUE TITLE
大佬，你好我想基于你的框架二次开发一下自己的东西，重新写了数据库使用插件生成代码的时候出错了，可以帮忙看看吗？

### ISSUE THREAD

**Issue by dongyi0412** [ixrjog/caesar#7]
[ERROR] Failed to execute goal on project caesar-service: Could not resolve dependencies for project com.baiyi:caesar-service:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.baiyi:caesar-domain:jar:0.0.1-SNAPSHOT: Failed to read artifact descriptor for com.baiyi:caesar-domain:jar:0.0.1-SNAPSHOT: Could not transfer artifact com.baiyi:caesar-domain:pom:0.0.1-SNAPSHOT from/to rdc-snapshots (https://packages.aliyun.com/maven/repository/2092263-snapshot-2W1UR8/): Authentication failed for https://packages.aliyun.com/maven/repository/2092263-snapshot-2W1UR8/com/baiyi/caesar-domain/0.0.1-SNAPSHOT/caesar-domain-0.0.1-SNAPSHOT.pom 401 Unauthorized -> [Help 1]

**Comment by dongyi0412** [comment]
看起来是依赖导入出错。但是好像不太理解 ，为什么会这样。是下载你们仓库包了么？

**Comment by ixrjog** [comment]
401是nexus鉴权错误

**Comment by dongyi0412** [comment]
我查了下找了找， 这个mybatis - generator 生成代码就在 domain service   2个模块下 不应该去仓库下包




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月20日(星期一) 晚上7:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ixrjog/caesar] 大佬，你好我想基于你的框架二次开发一下自己的东西，重新写了数据库使用插件生成代码的时候出错了，可以帮忙看看吗？ (Issue #7)





 
401是nexus鉴权错误

**Comment by ixrjog** [comment]
你应该执行mvn install

**Comment by dongyi0412** [comment]
是的，我重新支持了clean 和install 就好了。感谢回复，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月20日(星期一) 晚上10:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ixrjog/caesar] 大佬，你好我想基于你的框架二次开发一下自己的东西，重新写了数据库使用插件生成代码的时候出错了，可以帮忙看看吗？ (Issue #7)





 
你应该执行mvn install
